### ISSUE TITLE
split on the cassette & handle b sides properly

### ISSUE THREAD

**Issue by EmeraldSnorlax** [devilfreak/cas-farewell#7]
some runners go for 5b and/or 6b, so it'd be neat if this could also split on the cassette

**Comment by EmeraldSnorlax** [comment]
as of right now, it seems broken
it splits temple on returning to map after picking up the cassette and then seems to ignore the time spent in the b-side?
https://youtu.be/RHB_ZrNEqsI?t=1476

**Comment by devilfreak** [comment]
would it be better to make an extra split for the b side or should both be in one split?

**Comment by EmeraldSnorlax** [comment]
seperate: 5A start -> Cassette is one Split, and then 5B -> end is another split
should also be configurable to any of (5A or 5B) and (6A or 6B)
